import type { SidebarConfig } from '@vuepress/theme-default'

export const sidebar: SidebarConfig = {
  '/about/': [
    {
      text: '关于',
      children: ['/about/README.md', '/about/demo.md/'],
    },
  ],
  '/dev/': [
    {
      text: 'JDP平台',
      link: '/dev/jdp/',
      children: [
        '/dev/jdp/系统模块管理.md',
        '/dev/jdp/表结构管理.md',
        '/dev/jdp/报表设置.md',
        '/dev/jdp/枚举管理.md',
        '/dev/jdp/字段映射关系.md',
      ],
    },
    {
      text: 'config',
      link: '/dev/jdp/README.md',
      children: ['/dev/jdp/define.md', '/dev/jdp/popup.md'],
    },
    {
      text: '数据库',
      link: '/dev/jdp/README.md',
      children: [
        '/dev/jdp/存储过程.md',
        '/dev/jdp/视图.md',
        '/dev/jdp/标量值函数.md',
      ],
    },
    {
      text: '常见问题',
      collapsible: true,
      children: [
        '/dev/qa/README.md',
        '/dev/qa/usage-of-client-config.md',
        '/dev/qa/adding-extra-pages.md',
        '/dev/qa/making-a-theme-extendable.md',
        '/dev/qa/passing-data-to-client-code.md',
        '/dev/qa/markdown-and-vue-sfc.md',
      ],
    },
    {
      text: '尽消存帮助文档',
      link: '/help/jxc/',
    },
  ],
  '/help/jxc/': [
    {
      text: '尽消存帮助文档',
      link: '/help/jxc/',
    },
    {
      text: '购货管理',
      collapsible: true,
      children: [
        '/help/jxc/buy/购货询价.md',
        '/help/jxc/buy/购货申请.md',
        '/help/jxc/buy/申请汇总.md',
        '/help/jxc/buy/购货订单.md',
        '/help/jxc/buy/购货入库.md',
        '/help/jxc/buy/付款单.md',
        '/help/jxc/buy/购货换货.md',
        '/help/jxc/buy/购货退货.md',
        '/help/jxc/buy/购货明细报表.md',
        '/help/jxc/buy/购货统计表.md',
      ],
    },
    {
      text: '销货管理',
      collapsible: true,
      children: [
        '/help/jxc/sale/销货报价.md',
        '/help/jxc/sale/销货订单.md',
        '/help/jxc/sale/销货出库.md',
        '/help/jxc/sale/销货退货.md',
        '/help/jxc/sale/销货换货.md',
        '/help/jxc/sale/收款单.md',
        '/help/jxc/sale/销货明细报表.md',
        '/help/jxc/sale/销货统计表.md',
      ],
    },
    {
      text: '仓库管理',
      collapsible: true,
      children: [
        '/help/jxc/stock/成本调整.md',
        '/help/jxc/stock/其他出库.md',
        '/help/jxc/stock/其他入库.md',
        '/help/jxc/stock/同价调拨.md',
        '/help/jxc/stock/变价调拨.md',
        '/help/jxc/stock/组拆装单.md',
        '/help/jxc/stock/盘点流程.md',
        '/help/jxc/stock/盘点录入.md',
        '/help/jxc/stock/盘盈盘亏.md',
        '/help/jxc/stock/仓库明细报表.md',
        '/help/jxc/stock/库存报表.md',
      ],
    },
    {
      text: '财务管理',
      collapsible: true,
      children: [
        '/help/jxc/financial/付款单.md',
        '/help/jxc/financial/收款单.md',
        '/help/jxc/financial/费用支出.md',
        '/help/jxc/financial/其他收入.md',
        '/help/jxc/financial/凭证管理.md',
        '/help/jxc/financial/现金银行转账.md',
        '/help/jxc/financial/应付调账单.md',
        '/help/jxc/financial/应收调账单.md',
        '/help/jxc/financial/应收转应付.md',
        '/help/jxc/financial/应付转应收.md',
        '/help/jxc/financial/财务明细表.md',
        '/help/jxc/financial/财务报表.md',
      ],
    },
    {
      text: '系统设置',
      collapsible: true,
      children: [
        '/help/jxc/system/基础资料.md',
        '/help/jxc/system/财务信息.md',
        '/help/jxc/system/期初建账.md',
        '/help/jxc/system/结存.md',
        '/help/jxc/system/高级设置.md',
      ],
    },
    {
      text: '尽消存常见问题',
      collapsible: true,
      children: [
        '/help/jxc/qa/buyqa.md',
        '/help/jxc/qa/saleqa.md',
        '/help/jxc/qa/stockqa.md',
        '/help/jxc/qa/financialqa.md',
        '/help/jxc/qa/systemqa.md',
        '/help/jxc/qa/printqa.md',
      ],
    },
    {
      text: '打印样式设计',
      link: '/help/jxc/print/',
    },
    {
      text: '尽消存开发文档',
      link: '/dev/jdp/',
    },
  ],
  '/help/gjp/': [
    {
      text: '管家婆帮助文档',
      children: ['/help/gjp/hh/', '/help/gjp/gmt/'],
    },
  ],
  '/help/gjp/hh/': [
    {
      text: '管家婆帮助文档',
      link: '/help/gjp/',
      children: [
        '/help/gjp/hh/',
        '/help/gjp/hh/系统安装与日常维护.md',
        '/help/gjp/hh/系统维护与权限设置.md',
        '/help/gjp/hh/基本信息和期初建账.md',
        '/help/gjp/hh/进货管理.md',
        '/help/gjp/hh/销售管理.md',
        '/help/gjp/hh/零售管理.md',
        '/help/gjp/hh/库存管理.md',
        '/help/gjp/hh/往来管理.md',
        '/help/gjp/hh/账务管理.md',
        '/help/gjp/hh/代销业务.md',
        '/help/gjp/hh/借欠业务.md',
        '/help/gjp/hh/委外加工.md',
        '/help/gjp/hh/组合套件销售.md',
        '/help/gjp/hh/配送中心.md',
        '/help/gjp/hh/生产组装.md',
        '/help/gjp/hh/实物仓库.md',
        '/help/gjp/hh/固定资产.md',
        '/help/gjp/hh/总账管理.md',
        '/help/gjp/hh/其他功能.md',
        '/help/gjp/hh/辅助功能.md',
        '/help/gjp/hh/客户关系.md',
        '/help/gjp/hh/数据接口.md',
        '/help/gjp/hh/辉煌II特色功能.md',
        '/help/gjp/hh/五金建材版特色功能.md',
        '/help/gjp/hh/皮革布匹版特色功能.md',
        '/help/gjp/hh/电脑通讯版特色功能.md',
        '/help/gjp/hh/附件.md',
      ],
    },
  ],
  '/help/gjp/gmt/': [
    {
      text: '管家婆帮助文档',
      link: '/help/gjp/',
    },
    {
      text: '工贸T系列',
      link: '/help/gjp/gmt/',
    },
    {
      text: '文件',
      collapsible: true,
      children: [
        '/help/gjp/gmt/file/打开账套.md',
        '/help/gjp/gmt/file/更换操作员.md',
        '/help/gjp/gmt/file/修改口令.md',
        '/help/gjp/gmt/file/账套选项.md',
        '/help/gjp/gmt/file/操作员授权.md',
        '/help/gjp/gmt/file/基本信息授权.md',
        '/help/gjp/gmt/file/单据审核设置.md',
        '/help/gjp/gmt/file/单据格式配置.md',
        '/help/gjp/gmt/file/单据编号格式设置.md',
        '/help/gjp/gmt/file/序列号自动生成规则.md',
        '/help/gjp/gmt/file/导入导出.md',
        '/help/gjp/gmt/file/账套维护.md',
        '/help/gjp/gmt/file/安全钥匙.md',
        '/help/gjp/gmt/file/年结存.md',
        '/help/gjp/gmt/file/系统日志.md',
        '/help/gjp/gmt/file/关于.md',
        '/help/gjp/gmt/file/退出.md',
      ],
    },
    {
      text: '期初',
      collapsible: true,
      children: [
        '/help/gjp/gmt/BeginningOfThePeriod/期初单据查询.md',
        '/help/gjp/gmt/BeginningOfThePeriod/库存期初.md',
        '/help/gjp/gmt/BeginningOfThePeriod/实物仓库期初.md',
        '/help/gjp/gmt/BeginningOfThePeriod/委托代销期初.md',
        '/help/gjp/gmt/BeginningOfThePeriod/车间材料期初.md',
        '/help/gjp/gmt/BeginningOfThePeriod/委外材料期初.md',
        '/help/gjp/gmt/BeginningOfThePeriod/生产任务单.md',
        '/help/gjp/gmt/BeginningOfThePeriod/委外加工单.md',
        '/help/gjp/gmt/BeginningOfThePeriod/委外加工费用单.md',
        '/help/gjp/gmt/BeginningOfThePeriod/简单委外加工单.md',
        '/help/gjp/gmt/BeginningOfThePeriod/期初未结算单.md',
        '/help/gjp/gmt/BeginningOfThePeriod/期初账务数据.md',
        '/help/gjp/gmt/BeginningOfThePeriod/期初报表.md',
        '/help/gjp/gmt/BeginningOfThePeriod/期初结账.md',
        '/help/gjp/gmt/BeginningOfThePeriod/期初反结账.md',
      ],
    },
    {
      text: '基础资料',
      collapsible: true,
      children: [
        '/help/gjp/gmt/BasicData/常用操作.md',
        '/help/gjp/gmt/BasicData/基础资料规则设置.md',
        '/help/gjp/gmt/BasicData/存货资料.md',
        '/help/gjp/gmt/BasicData/售价管理.md',
        '/help/gjp/gmt/BasicData/存货数量采购价.md',
        '/help/gjp/gmt/BasicData/客户.md',
        '/help/gjp/gmt/BasicData/供应商.md',
        '/help/gjp/gmt/BasicData/地区.md',
        '/help/gjp/gmt/BasicData/部门.md',
        '/help/gjp/gmt/BasicData/职员.md',
        '/help/gjp/gmt/BasicData/仓库.md',
        '/help/gjp/gmt/BasicData/货位.md',
        '/help/gjp/gmt/BasicData/生产资料.md',
        '/help/gjp/gmt/BasicData/委外加工单价.md',
        '/help/gjp/gmt/BasicData/财务资料.md',
        '/help/gjp/gmt/BasicData/项目.md',
        '/help/gjp/gmt/BasicData/自定义档案.md',
        '/help/gjp/gmt/BasicData/常用摘要.md',
      ],
    },
    {
      text: '业务处理',
      collapsible: true,
      children: [
        '/help/gjp/gmt/business/单据基本操作.md',
        '/help/gjp/gmt/business/采购业务.md',
        '/help/gjp/gmt/business/销售业务.md',
        '/help/gjp/gmt/business/库存业务.md',
        '/help/gjp/gmt/business/实物仓库.md',
        '/help/gjp/gmt/business/质检管理.md',
        '/help/gjp/gmt/business/生产管理.md',
        '/help/gjp/gmt/business/委外加工.md',
        '/help/gjp/gmt/business/简单委外加工.md',
        '/help/gjp/gmt/business/设备工具管理.md',
        '/help/gjp/gmt/business/往来管理.md',
        '/help/gjp/gmt/business/费用管理.md',
        '/help/gjp/gmt/business/委托代销.md',
        '/help/gjp/gmt/business/其他业务.md',
        '/help/gjp/gmt/business/银行存取款.md',
        '/help/gjp/gmt/business/业务录入.md',
        '/help/gjp/gmt/business/单据审核中心.md',
        '/help/gjp/gmt/business/成本管理.md',
        '/help/gjp/gmt/business/月末处理.md',
      ],
    },
    {
      text: '业务报表',
      collapsible: true,
      children: [
        '/help/gjp/gmt/BusinessReport/业务报表基本操作.md',
        '/help/gjp/gmt/BusinessReport/草稿查询.md',
        '/help/gjp/gmt/BusinessReport/单据查找.md',
        '/help/gjp/gmt/BusinessReport/单据统计.md',
        '/help/gjp/gmt/BusinessReport/单据审核查询.md',
        '/help/gjp/gmt/BusinessReport/业务明细查询.md',
        '/help/gjp/gmt/BusinessReport/采购报表.md',
        '/help/gjp/gmt/BusinessReport/销售报表.md',
        '/help/gjp/gmt/BusinessReport/库存报表.md',
        '/help/gjp/gmt/BusinessReport/实物仓库报表.md',
        '/help/gjp/gmt/BusinessReport/质检报表.md',
        '/help/gjp/gmt/BusinessReport/生产报表.md',
        '/help/gjp/gmt/BusinessReport/委外加工报表.md',
        '/help/gjp/gmt/BusinessReport/设备工具管理.md',
        '/help/gjp/gmt/BusinessReport/客户往来报表.md',
        '/help/gjp/gmt/BusinessReport/供应商往来报表.md',
        '/help/gjp/gmt/BusinessReport/委托业务报表.md',
        '/help/gjp/gmt/BusinessReport/开票报表.md',
        '/help/gjp/gmt/BusinessReport/费用报表.md',
        '/help/gjp/gmt/BusinessReport/成本查询分析.md',
        '/help/gjp/gmt/BusinessReport/报警簿.md',
      ],
    },
    {
      text: '总账',
      collapsible: true,
      children: [
        '/help/gjp/gmt/GeneralLedger/常用凭证.md',
        '/help/gjp/gmt/GeneralLedger/凭证录入.md',
        '/help/gjp/gmt/GeneralLedger/出纳签字.md',
        '/help/gjp/gmt/GeneralLedger/审核.md',
        '/help/gjp/gmt/GeneralLedger/记账.md',
        '/help/gjp/gmt/GeneralLedger/凭证引入.md',
        '/help/gjp/gmt/GeneralLedger/凭证查找.md',
        '/help/gjp/gmt/GeneralLedger/汇兑损益.md',
        '/help/gjp/gmt/GeneralLedger/结转损益.md',
        '/help/gjp/gmt/GeneralLedger/期末结账.md',
        '/help/gjp/gmt/GeneralLedger/辅助工具.md',
        '/help/gjp/gmt/GeneralLedger/账表打印.md',
      ],
    },
    {
      text: '财务报表',
      collapsible: true,
      children: [
        '/help/gjp/gmt/FinancialStatements/日记账.md',
        '/help/gjp/gmt/FinancialStatements/年度损益统计.md',
        '/help/gjp/gmt/FinancialStatements/明细分类账.md',
        '/help/gjp/gmt/FinancialStatements/总分类账.md',
        '/help/gjp/gmt/FinancialStatements/多栏账.md',
        '/help/gjp/gmt/FinancialStatements/科目汇总表.md',
        '/help/gjp/gmt/FinancialStatements/科目余额表.md',
        '/help/gjp/gmt/FinancialStatements/辅助核算汇总表.md',
        '/help/gjp/gmt/FinancialStatements/辅助核算二维表.md',
        '/help/gjp/gmt/FinancialStatements/部门损益表.md',
        '/help/gjp/gmt/FinancialStatements/项目损益表.md',
        '/help/gjp/gmt/FinancialStatements/职员账.md',
        '/help/gjp/gmt/FinancialStatements/部门账.md',
        '/help/gjp/gmt/FinancialStatements/客户账.md',
        '/help/gjp/gmt/FinancialStatements/供应商账.md',
        '/help/gjp/gmt/FinancialStatements/项目账.md',
        '/help/gjp/gmt/FinancialStatements/项目分析.md',
        '/help/gjp/gmt/FinancialStatements/资产负债表.md',
        '/help/gjp/gmt/FinancialStatements/利润表.md',
        '/help/gjp/gmt/FinancialStatements/现金流量表.md',
        '/help/gjp/gmt/FinancialStatements/自定义报表.md',
        '/help/gjp/gmt/FinancialStatements/业务财务对照表.md',
        '/help/gjp/gmt/FinancialStatements/财务分析.md',
      ],
    },
    {
      text: '出纳管理',
      link: '/help/gjp/gmt/Cashier/',
    },
    {
      text: '工资管理',
      link: '/help/gjp/gmt/Wages/',
    },
    {
      text: '固定资产',
      link: '/help/gjp/gmt/FixedAssets/',
    },
    {
      text: '窗口',
      link: '/help/gjp/gmt/Window/',
    },
    {
      text: '应用中心',
      link: '/help/gjp/gmt/Plugin/',
    },
    {
      text: '常用功能',
      link: '/help/gjp/gmt/常用功能.md',
    },
  ],
}
