import type { SidebarConfig } from '@vuepress/theme-default'

export const sidebar: SidebarConfig = {
  '/about/': [
    {
      text: '关于',
      children: ['/about/README.md', '/about/demo.md/'],
    },
  ],
  '/dev/': [
    {
      text: 'JDP平台',
      link: '/dev/jdp/',
      children: [
        '/dev/jdp/module.md',
        '/dev/jdp/table.md',
        '/dev/jdp/report.md',
        '/dev/jdp/enumeration.md',
        '/dev/jdp/mapping.md',
      ],
    },
    {
      text: 'config',
      link: '/dev/jdp/README.md',
      children: ['/dev/jdp/define.md', '/dev/jdp/popup.md'],
    },
    {
      text: '数据库',
      link: '/dev/jdp/README.md',
      children: ['/dev/jdp/procedure.md', '/dev/jdp/view.md'],
    },
    {
      text: '常见问题',
      collapsible: true,
      children: [
        '/dev/qa/README.md',
        '/dev/qa/usage-of-client-config.md',
        '/dev/qa/adding-extra-pages.md',
        '/dev/qa/making-a-theme-extendable.md',
        '/dev/qa/passing-data-to-client-code.md',
        '/dev/qa/markdown-and-vue-sfc.md',
      ],
    },
    {
      text: '尽消存帮助文档',
      link: '/help/jxc/',
    },
  ],
  '/help/jxc/': [
    {
      text: '尽消存帮助文档',
      link: '/help/jxc/',
    },
    {
      text: '购货管理',
      collapsible: true,
      children: [
        '/help/jxc/buy/购货询价.md',
        '/help/jxc/buy/购货申请.md',
        '/help/jxc/buy/申请汇总.md',
        '/help/jxc/buy/购货订单.md',
        '/help/jxc/buy/购货入库.md',
        '/help/jxc/buy/付款单.md',
        '/help/jxc/buy/购货换货.md',
        '/help/jxc/buy/购货退货.md',
        '/help/jxc/buy/购货明细报表.md',
        '/help/jxc/buy/购货统计表.md',
      ],
    },
    {
      text: '销货管理',
      collapsible: true,
      children: [
        '/help/jxc/sale/销货报价.md',
        '/help/jxc/sale/销货订单.md',
        '/help/jxc/sale/销货出库.md',
        '/help/jxc/sale/销货退货.md',
        '/help/jxc/sale/销货换货.md',
        '/help/jxc/sale/收款单.md',
        '/help/jxc/sale/销货明细报表.md',
        '/help/jxc/sale/销货统计表.md',
      ],
    },
    {
      text: '仓库管理',
      collapsible: true,
      children: [
        '/help/jxc/stock/成本调整.md',
        '/help/jxc/stock/其他出库.md',
        '/help/jxc/stock/其他入库.md',
        '/help/jxc/stock/同价调拨.md',
        '/help/jxc/stock/变价调拨.md',
        '/help/jxc/stock/组拆装单.md',
        '/help/jxc/stock/盘点流程.md',
        '/help/jxc/stock/盘点录入.md',
        '/help/jxc/stock/盘盈盘亏.md',
        '/help/jxc/stock/仓库明细报表.md',
        '/help/jxc/stock/库存报表.md',
      ],
    },
    {
      text: '财务管理',
      collapsible: true,
      children: [
        '/help/jxc/financial/付款单.md',
        '/help/jxc/financial/收款单.md',
        '/help/jxc/financial/费用支出.md',
        '/help/jxc/financial/其他收入.md',
        '/help/jxc/financial/凭证管理.md',
        '/help/jxc/financial/现金银行转账.md',
        '/help/jxc/financial/应付调账单.md',
        '/help/jxc/financial/应收调账单.md',
        '/help/jxc/financial/应收转应付.md',
        '/help/jxc/financial/应付转应收.md',
        '/help/jxc/financial/财务明细表.md',
        '/help/jxc/financial/财务报表.md',
      ],
    },
    {
      text: '系统设置',
      collapsible: true,
      children: [
        '/help/jxc/system/基础资料.md',
        '/help/jxc/system/财务信息.md',
        '/help/jxc/system/期初建账.md',
        '/help/jxc/system/结存.md',
        '/help/jxc/system/高级设置.md',
      ],
    },
    {
      text: '尽消存常见问题',
      collapsible: true,
      children: [
        '/help/jxc/qa/buyqa.md',
        '/help/jxc/qa/saleqa.md',
        '/help/jxc/qa/stockqa.md',
        '/help/jxc/qa/financialqa.md',
        '/help/jxc/qa/systemqa.md',
        '/help/jxc/qa/printqa.md',
      ],
    },
    {
      text: '尽消存开发文档',
      link: '/dev/jdp/',
    },
  ],
  '/help/gjp/': [
    {
      text: '辉煌系列',
      collapsible: true,
      children: [
        '/help/gjp/hh/欢迎.md',
        '/help/gjp/hh/系统安装与日常维护.md',
        '/help/gjp/hh/系统维护与权限设置.md',
        '/help/gjp/hh/基本信息和期初建账.md',
        '/help/gjp/hh/进货管理.md',
        '/help/gjp/hh/销售管理.md',
        '/help/gjp/hh/零售管理.md',
        '/help/gjp/hh/库存管理.md',
        '/help/gjp/hh/往来管理.md',
        '/help/gjp/hh/账务管理.md',
        '/help/gjp/hh/代销业务.md',
        '/help/gjp/hh/借欠业务.md',
        '/help/gjp/hh/委外加工.md',
        '/help/gjp/hh/组合套件销售.md',
        '/help/gjp/hh/配送中心.md',
        '/help/gjp/hh/生产组装.md',
        '/help/gjp/hh/实物仓库.md',
        '/help/gjp/hh/固定资产.md',
        '/help/gjp/hh/总账管理.md',
        '/help/gjp/hh/其他功能.md',
        '/help/gjp/hh/辅助功能.md',
        '/help/gjp/hh/客户关系.md',
        '/help/gjp/hh/数据接口.md',
        '/help/gjp/hh/辉煌II特色功能.md',
        '/help/gjp/hh/五金建材版特色功能.md',
        '/help/gjp/hh/皮革布匹版特色功能.md',
        '/help/gjp/hh/电脑通讯版特色功能.md',
        '/help/gjp/hh/附件.md',
      ],
    },
    {
      text: '分销V系列',
      collapsible: true,
      children: [
        '/help/gjp/hh/pjb/',
        '/help/gjp/hh/pjii/',
        '/help/gjp/hh/hhii/',
        '/help/gjp/hh/hhii+/',
      ],
    },
    {
      text: '分销S系列',
      collapsible: true,
      children: [
        '/help/gjp/hh/pjb/',
        '/help/gjp/hh/pjii/',
        '/help/gjp/hh/hhii/',
        '/help/gjp/hh/hhii+/',
      ],
    },
    {
      text: '财贸双全财务版',
      collapsible: true,
      children: [
        '/help/gjp/cm/cwb/',
        '/help/gjp/cm/cwb/',
        '/help/gjp/cm/cwb/',
        '/help/gjp/cm/cwb/',
        '/help/gjp/cm/cwb/',
      ],
    },
    {
      text: '财贸双全系列',
      collapsible: true,
      children: [
        '/help/gjp/cm/sq/',
        '/help/gjp/cm/sq/',
        '/help/gjp/cm/sq/',
        '/help/gjp/cm/sq/',
        '/help/gjp/cm/sq/',
      ],
    },
    {
      text: '财贸C系列',
      collapsible: true,
      children: [
        '/help/gjp/cm/c/wj.md',
        '/help/gjp/cm/c/qc.md',
        '/help/gjp/cm/c/jczl.md',
        '/help/gjp/cm/c/ywcl.md',
        '/help/gjp/cm/c/ywbb.md',
      ],
    },
    {
      text: '工贸T系列',
      collapsible: true,
      children: [
        '/help/gjp/cm/t/wj.md',
        '/help/gjp/cm/t/qc.md',
        '/help/gjp/cm/t/jczl.md',
        '/help/gjp/cm/t/ywcl.md',
        '/help/gjp/cm/t/ywbb.md',
      ],
    },
    {
      text: '工贸M系列',
      collapsible: true,
      children: [
        '/help/gjp/cm/m/',
        '/help/gjp/cm/m/',
        '/help/gjp/cm/m/',
        '/help/gjp/cm/m/',
        '/help/gjp/cm/m/',
      ],
    },
    {
      text: '工贸PRO',
      collapsible: true,
      children: [
        '/help/gjp/cm/pro/',
        '/help/gjp/cm/pro/',
        '/help/gjp/cm/pro/',
        '/help/gjp/cm/pro/',
        '/help/gjp/cm/pro/',
      ],
    },
  ],
}
