import type { SidebarConfig } from '@vuepress/theme-default'

export const sidebar: SidebarConfig = {
  '/a/': [
    {
      text: '关于',
      children: ['/a/README.md', '/a/demo.md/'],
    },
  ],
  '/d/': [
    {
      text: 'JDP平台',
      link: '/d/j/',
      children: [
        '/d/j/a.md',
        '/d/j/b.md',
        '/d/j/c.md',
        '/d/j/d.md',
        '/d/j/e.md',
      ],
    },
    {
      text: 'config',
      link: '/d/j/1.md',
      children: ['/d/j/f.md', '/d/j/g.md'],
    },
    {
      text: '数据库',
      link: '/d/j/2.md',
      children: ['/d/j/h.md', '/d/j/i.md', '/d/j/j.md', '/d/j/k.md'],
    },
    {
      text: '常见问题',
      link: '/d/j/z/',
    },
    {
      text: '尽消存帮助文档',
      link: '/h/j/',
    },
  ],
  '/h/j/': [
    {
      text: '尽消存帮助文档',
      link: '/h/j/',
    },
    {
      text: '购货管理',
      collapsible: true,
      children: [
        '/h/j/a/a.md',
        '/h/j/a/b.md',
        '/h/j/a/c.md',
        '/h/j/a/d.md',
        '/h/j/a/e.md',
        '/h/j/a/f.md',
        '/h/j/a/g.md',
        '/h/j/a/h.md',
        '/h/j/a/i.md',
        '/h/j/a/j.md',
      ],
    },
    {
      text: '销货管理',
      collapsible: true,
      children: [
        '/h/j/b/a.md',
        '/h/j/b/b.md',
        '/h/j/b/c.md',
        '/h/j/b/d.md',
        '/h/j/b/e.md',
        '/h/j/b/f.md',
        '/h/j/b/g.md',
        '/h/j/b/h.md',
      ],
    },
    {
      text: '仓库管理',
      collapsible: true,
      children: [
        '/h/j/c/a.md',
        '/h/j/c/b.md',
        '/h/j/c/c.md',
        '/h/j/c/d.md',
        '/h/j/c/e.md',
        '/h/j/c/f.md',
        '/h/j/c/g.md',
        '/h/j/c/h.md',
        '/h/j/c/i.md',
        '/h/j/c/j.md',
        '/h/j/c/k.md',
      ],
    },
    {
      text: '财务管理',
      collapsible: true,
      children: [
        '/h/j/d/a.md',
        '/h/j/d/b.md',
        '/h/j/d/c.md',
        '/h/j/d/d.md',
        '/h/j/d/e.md',
        '/h/j/d/f.md',
        '/h/j/d/g.md',
        '/h/j/d/h.md',
        '/h/j/d/i.md',
        '/h/j/d/j.md',
        '/h/j/d/k.md',
        '/h/j/d/l.md',
      ],
    },
    {
      text: '系统设置',
      collapsible: true,
      children: [
        '/h/j/e/a.md',
        '/h/j/e/b.md',
        '/h/j/e/c.md',
        '/h/j/e/d.md',
        '/h/j/e/e.md',
      ],
    },
    {
      text: '尽消存常见问题',
      collapsible: true,
      children: [
        '/h/j/z/a.md',
        '/h/j/z/b.md',
        '/h/j/z/c.md',
        '/h/j/z/d.md',
        '/h/j/z/e.md',
        '/h/j/z/f.md',
      ],
    },
    {
      text: '打印样式设计',
      link: '/h/j/f/',
    },
    {
      text: '尽消存开发文档',
      link: '/d/j/',
    },
  ],
  '/h/g/': [
    {
      text: '管家婆帮助文档',
      children: ['/h/g/h/', '/h/g/t/'],
    },
  ],
  '/h/g/h/': [
    {
      text: '管家婆帮助文档',
      link: '/h/g/',
      children: [
        '/h/g/h/',
        '/h/g/h/a.md',
        '/h/g/h/b.md',
        '/h/g/h/c.md',
        '/h/g/h/d.md',
        '/h/g/h/e.md',
        '/h/g/h/f.md',
        '/h/g/h/g.md',
        '/h/g/h/h.md',
        '/h/g/h/i.md',
        '/h/g/h/j.md',
        '/h/g/h/k.md',
        '/h/g/h/l.md',
        '/h/g/h/m.md',
        '/h/g/h/n.md',
        '/h/g/h/o.md',
        '/h/g/h/p.md',
        '/h/g/h/q.md',
        '/h/g/h/r.md',
        '/h/g/h/s.md',
        '/h/g/h/t.md',
        '/h/g/h/u.md',
        '/h/g/h/v.md',
        '/h/g/h/w.md',
        '/h/g/h/x.md',
        '/h/g/h/y.md',
        '/h/g/h/z.md',
        '/h/g/h/1.md',
      ],
    },
  ],
  '/h/g/t/': [
    {
      text: '管家婆帮助文档',
      link: '/h/g/',
    },
    {
      text: '工贸T系列',
      link: '/h/g/t/',
    },
    {
      text: '文件',
      collapsible: true,
      children: [
        '/h/g/t/a/a.md',
        '/h/g/t/a/b.md',
        '/h/g/t/a/c.md',
        '/h/g/t/a/d.md',
        '/h/g/t/a/e.md',
        '/h/g/t/a/f.md',
        '/h/g/t/a/g.md',
        '/h/g/t/a/h.md',
        '/h/g/t/a/j.md',
        '/h/g/t/a/k.md',
        '/h/g/t/a/l.md',
        '/h/g/t/a/m.md',
        '/h/g/t/a/n.md',
        '/h/g/t/a/o.md',
        '/h/g/t/a/p.md',
        '/h/g/t/a/q.md',
      ],
    },
    {
      text: '期初',
      collapsible: true,
      children: [
        '/h/g/t/b/a.md',
        '/h/g/t/b/b.md',
        '/h/g/t/b/c.md',
        '/h/g/t/b/d.md',
        '/h/g/t/b/e.md',
        '/h/g/t/b/f.md',
        '/h/g/t/b/g.md',
        '/h/g/t/b/h.md',
        '/h/g/t/b/i.md',
        '/h/g/t/b/j.md',
        '/h/g/t/b/k.md',
        '/h/g/t/b/l.md',
        '/h/g/t/b/m.md',
        '/h/g/t/b/n.md',
        '/h/g/t/b/o.md',
      ],
    },
    {
      text: '基础资料',
      collapsible: true,
      children: [
        '/h/g/t/c/a.md',
        '/h/g/t/c/b.md',
        '/h/g/t/c/c.md',
        '/h/g/t/c/d.md',
        '/h/g/t/c/e.md',
        '/h/g/t/c/f.md',
        '/h/g/t/c/g.md',
        '/h/g/t/c/h.md',
        '/h/g/t/c/i.md',
        '/h/g/t/c/j.md',
        '/h/g/t/c/k.md',
        '/h/g/t/c/l.md',
        '/h/g/t/c/m.md',
        '/h/g/t/c/n.md',
        '/h/g/t/c/o.md',
        '/h/g/t/c/p.md',
        '/h/g/t/c/q.md',
        '/h/g/t/c/r.md',
      ],
    },
    {
      text: '业务处理',
      collapsible: true,
      children: [
        '/h/g/t/d/a.md',
        '/h/g/t/d/b.md',
        '/h/g/t/d/c.md',
        '/h/g/t/d/d.md',
        '/h/g/t/d/e.md',
        '/h/g/t/d/f.md',
        '/h/g/t/d/g.md',
        '/h/g/t/d/h.md',
        '/h/g/t/d/i.md',
        '/h/g/t/d/j.md',
        '/h/g/t/d/k.md',
        '/h/g/t/d/l.md',
        '/h/g/t/d/m.md',
        '/h/g/t/d/n.md',
        '/h/g/t/d/o.md',
        '/h/g/t/d/p.md',
        '/h/g/t/d/q.md',
        '/h/g/t/d/r.md',
        '/h/g/t/d/s.md',
      ],
    },
    {
      text: '业务报表',
      collapsible: true,
      children: [
        '/h/g/t/e/1.md',
        '/h/g/t/e/2.md',
        '/h/g/t/e/3.md',
        '/h/g/t/e/4.md',
        '/h/g/t/e/5.md',
        '/h/g/t/e/6.md',
        '/h/g/t/e/7.md',
        '/h/g/t/e/8.md',
        '/h/g/t/e/9.md',
        '/h/g/t/e/a.md',
        '/h/g/t/e/b.md',
        '/h/g/t/e/c.md',
        '/h/g/t/e/d.md',
        '/h/g/t/e/e.md',
        '/h/g/t/e/f.md',
        '/h/g/t/e/g.md',
        '/h/g/t/e/h.md',
        '/h/g/t/e/i.md',
        '/h/g/t/e/j.md',
        '/h/g/t/e/k.md',
        '/h/g/t/e/l.md',
      ],
    },
    {
      text: '总账',
      link: '/h/g/t/f/',
    },
    {
      text: '财务报表',
      collapsible: true,
      children: [
        '/h/g/t/f/a.md',
        '/h/g/t/f/b.md',
        '/h/g/t/f/c.md',
        '/h/g/t/f/d.md',
        '/h/g/t/f/e.md',
        '/h/g/t/f/f.md',
        '/h/g/t/f/g.md',
        '/h/g/t/f/h.md',
        '/h/g/t/f/i.md',
        '/h/g/t/f/j.md',
        '/h/g/t/f/k.md',
        '/h/g/t/f/l.md',
        '/h/g/t/f/m.md',
        '/h/g/t/f/n.md',
        '/h/g/t/f/o.md',
        '/h/g/t/f/p.md',
        '/h/g/t/f/q.md',
        '/h/g/t/f/r.md',
        '/h/g/t/f/s.md',
        '/h/g/t/f/t.md',
        '/h/g/t/f/u.md',
        '/h/g/t/f/v.md',
        '/h/g/t/f/w.md',
      ],
    },
    {
      text: '出纳管理',
      link: '/h/g/t/g/',
    },
    {
      text: '工资管理',
      link: '/h/g/t/h/',
    },
    {
      text: '固定资产',
      link: '/h/g/t/i/',
    },
    {
      text: '窗口',
      link: '/h/g/t/j/',
    },
    {
      text: '应用中心',
      link: '/h/g/t/k/',
    },
    {
      text: '常用功能',
      link: '/h/g/t/cygn.md',
    },
  ],
}
